[package]
name = "multitrack-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
pixels = "0.13.0"
winit = "0.28.6"
winit_input_helper = "0.14.1"
serde = { version = "1.0.164", features = [ "derive" ] }
serde_json = "1.0.97"
lazy_static = "1.4.0"
symphonia = { version = "0.5.3", features = [ "all-codecs" ] }
image = { version = "0.24.6", default-features = false, features = [ "png" ] }
